/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package novataboa.gui;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractSpinnerModel;
import javax.swing.JScrollBar;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import javax.swing.event.ChangeListener;
import novataboa.dto.Alumno;
import novataboa.loxica.ProcesoAlumnado;
import novataboa.modeloTabla.StudentTableModelGeneric;

/**
 *
 * @author manuel
 */
public class DialogoModif extends javax.swing.JDialog {

    PantallaPrincipal pantalla;
    private int fila=-1;
        
    public DialogoModif(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pantalla=(PantallaPrincipal) parent;
        formatoSpinner();
    }
    
    public DialogoModif(java.awt.Frame parent, boolean modal, int mod) {
        super(parent, modal);
        initComponents();
        this.pantalla=(PantallaPrincipal) parent;
        this.fila=mod;
        formatoSpinner();
       /* ModeloSpinner modelo = new ModeloSpinner(2020, 2021);
        jSpinner1Curso.setModel(modelo); */
        
    }
    
    private void formatoSpinner(){
        SpinnerDateModel modelo = new SpinnerDateModel();
        jSpinnerDataAlta.setModel(modelo);
        jSpinnerDataAlta.setEditor(new JSpinner.DateEditor(jSpinnerDataAlta, "dd/MM/yyyy"));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Nome = new javax.swing.JLabel();
        JLabeApelidos = new javax.swing.JLabel();
        jLabel3DataAlta = new javax.swing.JLabel();
        jTextApelidos = new javax.swing.JTextField();
        jTextField2Nome = new javax.swing.JTextField();
        jSpinnerDataAlta = new javax.swing.JSpinner();
        jLabel1Curso = new javax.swing.JLabel();
        jComboBox1Curso = new javax.swing.JComboBox<>();
        jButton1Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1Nome.setText("Nome");

        JLabeApelidos.setText("Apelidos");

        jLabel3DataAlta.setText("Data");

        jSpinnerDataAlta.setModel(new javax.swing.SpinnerDateModel());

        jLabel1Curso.setText("Curso");

        jComboBox1Curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019/2020", "2020/2021", "2021/2022" }));

        jButton1Ok.setText("OK");
        jButton1Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3DataAlta)
                                .addGap(63, 63, 63)
                                .addComponent(jSpinnerDataAlta))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabeApelidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextApelidos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1Curso)
                        .addGap(52, 52, 52)
                        .addComponent(jComboBox1Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Nome)
                    .addComponent(jTextField2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabeApelidos)
                    .addComponent(jTextApelidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3DataAlta)
                    .addComponent(jSpinnerDataAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Curso)
                    .addComponent(jComboBox1Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1Ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1OkActionPerformed
        if (this.fila!=-1)
            modificacion(fila);
        else
            darAlta();
        this.dispose();
    }//GEN-LAST:event_jButton1OkActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void darAlta() {
        String nome = jTextField2Nome.getText();
        String apelidos = jTextApelidos.getText();
        Date data = (Date)jSpinnerDataAlta.getValue();
        String curso = (String) jComboBox1Curso.getSelectedItem();
        Alumno alumno = new Alumno(nome, apelidos, data, curso);
        ProcesoAlumnado.engadirAlumno(alumno);
        pantalla.engadirALumno(alumno);
        
    }
    
    private void modificacion(int indexRow){
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
        
        String nome = jTextField2Nome.getText();
        String apelidos = jTextApelidos.getText();
        Date date = (Date)jSpinnerDataAlta.getValue();
        String data = sdf.format(date);
        String curso = (String)jComboBox1Curso.getSelectedItem();
        
        StudentTableModelGeneric modelo = ( StudentTableModelGeneric) pantalla.getjTable1().getModel();
        int viewIndex = pantalla.getjTable1().getSelectedRow();
        int modelIndex = pantalla.getjTable1().convertRowIndexToModel(viewIndex);
        Alumno alumnoMod = modelo.getDomainObject(modelIndex);
        alumnoMod.setNome(nome);

        alumnoMod.setApelidos(apelidos);
        alumnoMod.setCurso(curso);
        alumnoMod.setDataAlta(date);
        modelo.notifyDomainObjectUpdated(alumnoMod);


    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoModif dialog = new DialogoModif(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabeApelidos;
    private javax.swing.JButton jButton1Ok;
    private javax.swing.JComboBox<String> jComboBox1Curso;
    private javax.swing.JLabel jLabel1Curso;
    private javax.swing.JLabel jLabel1Nome;
    private javax.swing.JLabel jLabel3DataAlta;
    private javax.swing.JSpinner jSpinnerDataAlta;
    private javax.swing.JTextField jTextApelidos;
    private javax.swing.JTextField jTextField2Nome;
    // End of variables declaration//GEN-END:variables
}
